# Generated by Django 3.2.6 on 2021-08-26 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('distID', models.IntegerField(primary_key=True, serialize=False)),
                ('distName', models.CharField(max_length=10)),
                ('region', models.CharField(choices=[('NT', 'New Territories'), ('KLN', 'Kowloon'), ('HK', 'Hong Kong Island')], max_length=3)),
            ],
            options={
                'unique_together': {('distName', 'region')},
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('spID', models.IntegerField(primary_key=True, serialize=False)),
                ('spName', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('docID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('eMail', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('priceRemarks', models.CharField(max_length=30)),
                ('holidayRemarks', models.CharField(max_length=20)),
                ('dist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorAPI.district')),
                ('specializaton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorAPI.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactNo', models.CharField(max_length=13)),
                ('docID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorAPI.doctor')),
            ],
            options={
                'unique_together': {('docID', 'contactNo')},
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thusday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('docID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorAPI.doctor')),
            ],
            options={
                'unique_together': {('docID', 'day')},
            },
        ),
    ]
