# Generated by Django 3.2.6 on 2021-08-27 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specializaton',
            new_name='specialization',
        ),
    ]
